# Generated by Django 5.2.8 on 2025-12-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_size_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
