# Generated by Django 5.2.8 on 2025-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='bulb.jpg', null=True, upload_to='profiles/'),
        ),
    ]
